### ISSUE TITLE
[NavItem] Should always show “pointer” mouse cursor when has nested NavItems

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie#1]
### Currently

When `isCurrentPage`, the `href` attribute is not set on the NavItem `<a>` element (and `cursor: pointer` styling is only applies when `href` is present).

### Problem

When the NavItem has nested NavItems (i.e. a dropdown) the `pointer` mouse cursor should be shown, since the root NavItem should be clickable (to toggle the dropdown).

![iscurrentpage-navitem](https://user-images.githubusercontent.com/13482427/30918090-d8a80496-a39d-11e7-862a-f1debf4020cb.gif)

### Wanted

If we have `children`, set the `href` attribute even when `isCurrentPage`.

### Notes 

`isCurrentPage` is possibly the wrong name for this prop, since we might want to use it to indicate the current _section/category_ rather than the current page.

**Comment by conor-cafferkey-sociomantic** [comment]
For simplicity’s sake, let’s just keep the `href` here all the time

**Comment by tar-viturawong-sociomantic** [comment]
@eric-martinez-sociomantic @conor-cafferkey-sociomantic the commit 
e4bc41c completely `isCurrentPage`. Since this is effectively a breaking change, it cannot be bundled with Capybara. Instead, please respect SemVer and continue support for `isCurrentPage`.
