### ISSUE TITLE
[Slider] Add back in transitions 

### ISSUE THREAD

**Issue by damian-rodriguez-sociomantic** [sociomantic-tsunami/nessie#102]
### Currently

Slider doesn’t have transitions (we removed them due to a broken implementation).

### Wanted

Add transitions (in a non-broken way).

**Comment by conor-cafferkey-sociomantic** [comment]
> we removed them due to a broken implementation

Specifically, When we have two handles (range slider), there is a jarring effect where the animation of the track fill gets out of sync with the handle animations.

Let’s address this as part of the updated Slider styling.
