### ISSUE TITLE
[ Color Palette ] Labelling & Grey Scale

### ISSUE THREAD

**Issue by eric-martinez-sociomantic** [sociomantic-tsunami/nessie#130]
It will be ideal that the color definitions followed in Sketch and Zeplin and the color definitions on nessie will be aligned using the same variable codes. We should investigate it, doesn't seem complicated and there is some native support already in zeplin for this feature.

https://twitter.com/zeplin_io/status/702538738266673154?lang=en

This will mean to use variables in zeplin and sketch soo colors will be define as follows:

```
   /* primary colors */
    --PC-WHITE:     #ffffff;
    --PC-BLUE:       #19a2e2;
    --PC-GREEN:    #1bbab0;
    --PC-RED:         #ff5460;
    --PC-ORANGE: #ff7f5a;
    --PC-YELLOW: #ffb050;

    --PC-GREY:            var( --GS-5 );
    --PC-DARK-GREY: var( --GS-10 );

    /* greyscale colors */
    --GS-1:      color( var( --GS-5 ) shade( 35% ) );
    --GS-2:     color( var( --GS-5 ) shade( 25% ) );
    --GS-3:     color( var( --GS-5 ) shade( 15% ) );
    --GS-4:     color( var( --GS-5 ) shade( 5% ) );
    --GS-5:     #7594ae;
    --GS-6:     color( var( --GS-5 ) tint( 10% ) );
    --GS-7:     color( var( --GS-5 ) tint( 25% ) );
    --GS-8:     color( var( --GS-5 ) tint( 40% ) );
    --GS-9:     color( var( --GS-5 ) tint( 70% ) );
    --GS-10:   color( var( --GS-5 ) tint( 90% ) ); 
```

Also grey scale should follow the logic in the other scales and the main grey color should be placed in the middle of the scale as all the rest primary colors does.

![screen shot 2017-12-21 at 13 01 40](https://user-images.githubusercontent.com/17337153/34255238-0000b76e-e650-11e7-804f-dcb5cb02e03c.png)

**Comment by eric-martinez-sociomantic** [comment]
@tatevik-vasilyan-sociomantic

**Comment by tatevik-vasilyan-sociomantic** [comment]
@eric-martinez-sociomantic  The grey color swatch is the only exception. It doesn't follow the same logic as others, so we will need to define variables for each shade.
aaand we have variables for colors in Zeplin now ))
