### ISSUE TITLE
[Table] Table “align”, “gutters” and “spacing” props overriding TableRow/TableCell props

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie#136]
### Currently

The `align`, `gutters` and `spacing` props set on Table override those set on individual TableRows/TableCells.

### Problem

This makes it impossible to set those props for individual TableRows/TableCells (even the _default_ prop values coming from Table take precedence over the individual values).

### Wanted

Props set on individual TableRows/TableCells should take precedence over those set at Table level.

**Comment by ido-flaishon-sociomantic** [comment]
This affects also the reporting table. In our case also the first column is supposed to be sticky and it stops working.

Reminder: Once fixed we need to check if the `zebra` & `sticky` for the first column works for the reporting table component.

**Comment by ido-flaishon-sociomantic** [comment]
@damian-rodriguez-sociomantic @conor-cafferkey-sociomantic Please let me know to which Nessie version will this be deployed and if it's already deployed.

**Comment by damian-rodriguez-sociomantic** [comment]
This is already included in the latest nessie release ( v5.8.0 ).
FYI @ido-flaishon-sociomantic
