### ISSUE TITLE
[Exports] Export Nessie object as default

### ISSUE THREAD

**Issue by eric-martinez-sociomantic** [sociomantic-tsunami/nessie#15]
### Currently

We only export the individual components.

### Problem

If you want a `Nessie` object with all the components you have to do:
```import * as Nessie from 'nessie'```

### Wanted

Export a default object so you can simply do:
```import Nessie from 'nessie'```

This is breaking change and will require lochness, etc. to be aligned...

**Comment by conor-cafferkey-sociomantic** [comment]
Actually not a breaking change at, removing that label

**Comment by conor-cafferkey-sociomantic** [comment]
Maybe follow the same pattern as React uses for its export?

**Comment by conor-cafferkey-sociomantic** [comment]
superceded by: https://github.com/sociomantic-tsunami/nessie/issues/358
