### ISSUE TITLE
[ComboBox] Update styling

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie#173]
Update ComboBox styling in line with [updated FlounderDropdown styling](https://github.com/sociomantic-tsunami/nessie/issues/151).

This will involve updating the following components:
- Dropdown
- ListBox
    - ListBoxOptionGroup
    - ListBoxOption
- ScrollBox(?)
- TextInputWithIcon(?)

**Comment by daniel-martic-sociomantic** [comment]
Reopening for style updates.
