### ISSUE TITLE
[Code Editor] Max height

### ISSUE THREAD

**Issue by illia-kibalnyi-sociomantic** [sociomantic-tsunami/nessie#197]
Would be great to make available specifying max height for CodeEditor so it is not stretched all over the page and consistent with SD. Also would be great to have default value as 325px.

**Comment by conor-cafferkey-sociomantic** [comment]
Thanks for the issue @illia-kibalnyi-sociomantic!

I think we’d probably want two different props:
- `maxHeight` - height is auto up till specified height
- `height` - sets a fixed height (overrides `maxHeight`)

Actually, I’d suggest we do it like this instead:
- `maxLines` - limits the number of rows/lines shown after specified amount
- `lines` - fixed number of rows/lines shown (overrides `maxLines`)

(In general we’d like to avoid setting arbitrary pixel values.)

**Comment by tero-saarinen-sociomantic** [comment]
We recently discussed within ux for text-areas, that horizontal resizing should be prevented and vertical resizing would not be limited at all. I'd suggest applying the same for CodeEditors.
