### ISSUE TITLE
[Tooltip] Enlarge the hoverable area

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie#2]
### Currently
There is a 5px gap between between the Tooltip itself and the wrapped content that the tooltip is associated with (`children`).

### Problem

The gap makes it difficult to implement a behavior where you can hover over the tooltip itself to make it persist.

![3a179e60-3190-11e7-95c0-4352c83fb192](https://user-images.githubusercontent.com/13482427/31022701-e9203968-a539-11e7-9c68-8c3090f84c16.png)

### Wanted 

Increase hoverable area so that there is no gap between the wrapped content and the tooltip itself.

**Comment by conor-cafferkey-sociomantic** [comment]
After some testing it seems that the above hoverable area isn’t really sufficient. We’ll likely need to increase the hoverable area to cover the blue area below:

![screen shot 2017-10-19 at 18 20 46](https://user-images.githubusercontent.com/13482427/31816437-9cb988a6-b590-11e7-8d9d-a4fa3ed0d02d.png)

**Comment by eric-martinez-sociomantic** [comment]
@conor-cafferkey-sociomantic done.

**Comment by joppe-rhebergen-sociomantic** [comment]
@eric-martinez-sociomantic @conor-cafferkey-sociomantic thanks, this is working great 👍
