### ISSUE TITLE
[Slider] Error after component props update

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie#214]
### Currently
In `componentWillUpdate` we manually clear the array of refs to the native `<input>` elements (`this.inputs`) with the assumption that the those refs will get re-populated when the `render` method is called.

### Problem

__That’s not how refs work.__ 

After the component updates we get an error when we try to interact with the slider:
```
index.jsx:387 Uncaught TypeError: Cannot set property 'value' of undefined
    at Slider.handleMouseMove (index.jsx:387)
```

At this point `this.inputs` is empty because the new refs have not been stored.

### Wanted

Store the input refs in a sensible, non-broken way.

**Comment by kevin-krug-sociomantic** [comment]
@conor-cafferkey-sociomantic thanks for quickly jumping on this bug 💥 Unfortunately I'm still seeing a missing reference to the input in the `handleTrackMouseDown` handler, see my comment https://github.com/sociomantic-tsunami/nessie/commit/4b706ed2e947b33f13fa86add44f22b1e3d2823b#r27952287. Can you update the reference there as well, cheers!!

**Comment by conor-cafferkey-sociomantic** [comment]
OK I’ll make that fix now, thanks for catching!
