### ISSUE TITLE
[Slider] add driver

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/nessie#243]
### current
currently there is no driver for the slider component. 
### wanted
should be added in order to be utilised in our ursula presenter tests

**Comment by conor-cafferkey-sociomantic** [comment]
Well need at least the following driver methods (@kevin-krug-sociomantic please add to here as you see fit):

- `getInputValue()` - returns current value, or an array of values corresponding to slider handles
- `setInputValue( val )` - accepts a value, or an array of values

**Comment by kevin-krug-sociomantic** [comment]
@conor-cafferkey-sociomantic yes also a method to get all props, which could then internally be used to get the ticks and the stepLabels.

- `getTicks()`
- `getStepLabels()`

**Comment by conor-cafferkey-sociomantic** [comment]
Enzyme already provides [`props()`](http://airbnb.io/enzyme/docs/api/ReactWrapper/props.html) and [`prop([key])`](http://airbnb.io/enzyme/docs/api/ReactWrapper/prop.html) so we get those for free 😉

**Comment by kevin-krug-sociomantic** [comment]
that's great! but could still add the specific method `getTicks` and `getStepLabels`, thanks man!

**Comment by kevin-krug-sociomantic** [comment]
fair enough, then I'll use enzyme's out-of-the-box `props()`. I'll need a `clickMouseUp` driver method though to check when a value is committed. Can you add that, cheers!

**Comment by kevin-krug-sociomantic** [comment]
@conor-cafferkey-sociomantic is there an ETA for when this will be released? thanks again for the quick implementation
