### ISSUE TITLE
[Tests] Shallow renderer warning

### ISSUE THREAD

**Issue by daniel-martic-sociomantic** [sociomantic-tsunami/nessie#259]
When we run the tests (yarn test/yarn tdd) we get React warning:

`Warning: Shallow renderer has been moved to react-test-renderer/shallow. Update references to remove this warning.`

We need to update packages and references to solve Shallow renderer warning.

**Comment by conor-cafferkey-sociomantic** [comment]
This will require updating to Enzyme 3.x.y. 

Migration guide: https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md
