### ISSUE TITLE
[Checkbox] Driver

### ISSUE THREAD

**Issue by illia-kibalnyi-sociomantic** [sociomantic-tsunami/nessie#269]
Should provide such methods:

- `check()` - mark as checked
- `uncheck()` - mark as unchecked
- `toggle()` - mark as checked if unchecked or vice versa
- `isChecked()`
- `mouseOver()`
- `mouseOut()`
- `click()` - as an alias for toggle (edited)

**Comment by daniel-martic-sociomantic** [comment]
Commit `517b513` msg: " Removed `.only` from `tests.jsx` "
