### ISSUE TITLE
[Radio] Driver

### ISSUE THREAD

**Issue by illia-kibalnyi-sociomantic** [sociomantic-tsunami/nessie#270]
Should provide such methods:

- `check()` - mark as checked
- `uncheck()` - mark as unchecked
- `toggle()` - mark as checked if unchecked or vice versa
- `isChecked()`
- `mouseOver()`
- `mouseOut()`
- `click()` - as an alias for toggle (edited)

**Comment by daniel-martic-sociomantic** [comment]
Covered in #278
