### ISSUE TITLE
[RadioGroup] Driver

### ISSUE THREAD

**Issue by illia-kibalnyi-sociomantic** [sociomantic-tsunami/nessie#272]
Should provide such methods:

- `selectByIndex( index )` - select radio by index
- `selectByValue( value )` - select radio by value
- `getSelectedValue()` - returns selected value
- `mouseOverByIndex( index )`
- `mouseOverByValue( value )`
- `mouseOutByIndex( index )`
- `mouseOutByValue( value )`

**Comment by daniel-martic-sociomantic** [comment]
Covered in #271
