### ISSUE TITLE
[CheckableGroup] Driver Error

### ISSUE THREAD

**Issue by illia-kibalnyi-sociomantic** [sociomantic-tsunami/nessie#306]
Throws `TypeError: Cannot read property 'default' of undefined` when trying to get driver on RadioGroup.

Lines 6-7
```javascript
this.cssMap  = wrapper.props().cssMap;
this.outer   = wrapper.find( `.${wrapper.props().cssMap.default}` );
```

Seems like `cssMap` doesn't exist for `RadioGroup` and probably `CheckboxGroup` as well.

**Comment by daniel-martic-sociomantic** [comment]
True, `RadioGroup` and `CheckboxGroup` don't have `cssMap` ( it's `undefined` ) because both are wrapping `CheckableGroup` and don't have their own styles, so it should only be used on `CheckableGroup` instead.

**Comment by illia-kibalnyi-sociomantic** [comment]
@daniel-martic-sociomantic but nevertheless it's a bug, as I call driver on `RadioGroup` and get error
