### ISSUE TITLE
[Slider] driver - event target not the input el :bug:

### ISSUE THREAD

**Issue by kevin-krug-sociomantic** [sociomantic-tsunami/nessie#346]
for tests on Ursula's side, the event which is triggered by the change method of nessie's slider driver is just set to `target : { value }`, thus missing data attribute etc. (crucial for testing staging e.g.), or rather the event target should be the input html element.

see: https://github.com/sociomantic-tsunami/nessie/blob/master/src/Slider/driver.js#L41-L42

@conor-cafferkey-sociomantic thanks in advance for your fix!

**Comment by conor-cafferkey-sociomantic** [comment]
Yep, good catch! We should not be overriding the target. Looks like this same pattern is used in some of the other drivers so I’ll fix those too.
