### ISSUE TITLE
[Dropdown] Export the “withDropdown” higher-order component

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie#354]
### Currently

We have a [`withDropdown`](https://github.com/sociomantic-tsunami/nessie/blob/master/src/Dropdown/withDropdown.jsx) higher-order component to attach a dropdown to any given component.

### Problem

It’s [used internally](https://github.com/sociomantic-tsunami/nessie/blob/13fb26d6a454ba61cee7300648f51b09961df63f/src/ComboBox/index.jsx#L18) in Nessie but not exported, despite being very useful to consumers.

### Wanted

We should export the `withDropdown` HOC/function (and potentially other useful HOC’s).

I suggest we do this by making the `Dropdown` component itself a module whose default export is the Dropdown component but also has the `withDropdown` function as a named export.

**Comment by mahmoud-zakria-sociomantic** [comment]
> I suggest we do this by making the Dropdown component itself a module whose default export is the Dropdown component but also has the withDropdown function as a named export.

This doesn’t seem to be possible. Instead we’ll create a separate `addons.js` dist bundle.
