### ISSUE TITLE
[CodeEditor] Driver missing methods

### ISSUE THREAD

**Issue by illia-kibalnyi-sociomantic** [sociomantic-tsunami/nessie#363]
Please add such methods:
* `inputValue( value )` - changes the value without blur
* `pressKey( keyCode )` - simulates `keyPress` event

**Comment by conor-cafferkey-sociomantic** [comment]
As per [inputComponentDriver.js](https://github.com/sociomantic-tsunami/nessie/blob/master/src/Testing/CommonDrivers/inputComponentDriver.js) these methods should have the following behavior:

- `pressKey( keyCode )`:adds the character corresponding to `keyCode` to the end of value
- `inputValue( value )`: calls `pressKey( keyCode )` individually for each char of `value`
