### ISSUE TITLE
[ComboBox] Dropdown shows in wrong position when label is present

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie#367]
### Currently

When `dropdownPosition` is `'top'` and `label` is also defined, the dropdown is positioned relative to the label:

![screen shot 2018-05-16 at 09 26 46](https://user-images.githubusercontent.com/13482427/40102651-58925db6-58eb-11e8-8875-be0033946758.png)

### Wanted

The dropdown should always be positioned relative to the text input.

**Comment by mahmoud-zakria-sociomantic** [comment]
@conor-cafferkey-sociomantic  It seems that it doesn't exist on the `MinorChanges-Iguana`, but it shows in `Milestone-GlobalStyleUpdate`.
So the issue supposed to be on which branch?

**Comment by mahmoud-zakria-sociomantic** [comment]
Ok I've changed the milestone to be `Milestone-GlobalStyleUpdate`.
