### ISSUE TITLE
[Slider] Should be possible to click on track to jump to value

### ISSUE THREAD

**Issue by eric-martinez-sociomantic** [sociomantic-tsunami/nessie#37]
### Currently

You can only change the Slider value by dragging the handle. Clicking on the track does nothing.

### Problem

Inconsistent with native behavior / user expectations.

### Wanted

As with a native slider, clicking on the track should jump to the relevant value.

#### Implementation

Clicking on the track should work similarly to dragging the handle, that is:
1. compute new value
1. assign new value to the native `<input>`
1. dispatch a `change` event on the `<input>`
1. fire `onChange` with the dispatched event
1. `forceUpdate()`

This gets a bit more tricky when we have multiple handles with multiple `<input>`’s. In that case I guess step 2. should be: assign new value to the native `<input>` associated with the _last-selected_ handle (or, if no handle was previously selected, the first `<input>`).

**Comment by damian-rodriguez-sociomantic** [comment]
- [ ] Add transitions (in a non-broken way).
