### ISSUE TITLE
[Column/TableCell] Add “icon-S”, “icon-M”, etc.  as options for “size” prop

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie#47]
### Currently

The width of a Column (or TableCell) can be set via the `size` prop to either a fraction represented as a string (e.g. `size="2/4"`) or as the content width (`size="content"`). If no size is set the column widths are distributed evenly.

### Wanted

As discussed with @tar-viturawong-sociomantic, it would be useful to accept our Icon sizes in the `size` prop. E.g: `size="icon-S"` or `size="icon-L"`.

This could be used for table layouts where we have columns that contain icons (e.g. columns containing _Delete_ or _Edit_ IconButtons).

**Comment by eric-martinez-sociomantic** [comment]
@conor-cafferkey-sociomantic what is the difference here form implementing this fixed sizes or using the "content" prop? it isn't enough for this goal to use the "content"prop already implemented?

**Comment by conor-cafferkey-sociomantic** [comment]
Hey @eric-martinez-sociomantic, yep fair question, my description above didn't really make that clear.

The use case is when when we want a particular column to have the the size of an icon but we don't necessarily have any content in the table cells in that column. For example:

| Fruit  | Quantity| |
| ------------- | ------------- | -- |
| Apple  | 2000  | |
| Orange  | 1500  |  |
| Kiwi  | 15  | [+] |

In this example the  _[+]_ is an icon button that places an order for more Kiwis and that icon button is only shown when the quantity is below a certain amount.
