### ISSUE TITLE
[Tooltip] Add “isDismissible”, “onClickClose” props

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie#53]
### Currently

Tooltips are designed to be shown only on hover.

### Wanted

To enable tooltips to be displayed persistently until the user dismisses them we need `isDismissible`, `onClickClose` props.

When `isDismissible` is true we’ll show `<IconButton iconType="close"/>` in the top-right corner of the tooltip.

![screen shot 2017-08-10 at 18 33 19](https://user-images.githubusercontent.com/13482427/29181159-6f79f150-7dfa-11e7-8d6a-961d9afd14ef.png)

**Comment by conor-cafferkey-sociomantic** [comment]
This was never merged... 😕

**Comment by daniel-martic-sociomantic** [comment]
Implemented as part of Global Style Changes.
