### ISSUE TITLE
Provide minified bundles

### ISSUE THREAD

**Issue by joshuef** [sociomantic-tsunami/nessie#83]
This [issue](https://github.com/sociomantic-tsunami/nessie/issues/82) is part organisational. But also part sizing. 

Currently including nessie increases the bundle size drastically (by ~3mb). 

We should check for any quick wins to reduce compiled sizes etc. 
Also perhaps a minified version?

**Comment by conor-cafferkey-sociomantic** [comment]
A couple things I think we can improve here:
- As you say, minification (JS and CSS)
- Excluding Flounder and CodeMirror from the bundle (and also excluding the FlounderDropdown and CodeMirror components from the default export; they should be opt-in)

**Comment by joshuef** [comment]
> Excluding Flounder and CodeMirror from the bundle (and also excluding the FlounderDropdown and CodeMirror components from the default export; they should be opt-in)

Sounds good to me 👍 Couple with the shakes this will probably alleviate bundle bloat for consuming apps.
