### ISSUE TITLE
[Row] Should not have word-wrap: break-word

### ISSUE THREAD

**Issue by conor-cafferkey-sociomantic** [sociomantic-tsunami/nessie#98]
### Currently

All Rows get `word-wrap: break-word;`.

### Problem

This isn’t necessarily what we want

### Wanted

Remove `word-wrap: break-word;` or add a prop to control this.

**Comment by conor-cafferkey-sociomantic** [comment]
> or add a prop to control this.
If we do need this, it should probably be a prop of the Text component.

**Comment by eric-martinez-sociomantic** [comment]
Seem this functionality is already built in in the Text component, anyway I added it tot the Row as well so they can be configured either in the individual text or in the Row.
